### ISSUE TITLE
Thank you.

### ISSUE THREAD

**Issue by DeeJaVu** [miiikkeyyyy/larastart#1]
Thank you sir, this is the best laravel bootstrap starter skeleton.

**Comment by miiikkeyyyy** [comment]
Hello, DeeJaVu. 

Thank you very much! I've only spent two days working on it. 

I have an issue with refreshing the database (it fails to drop the roles table due to the foreign key). 

Just a reminder that I'm updating this on a daily basis. At the moment we are only in development mode :)
