### ISSUE TITLE
ReCAPTCHA isn't showing up on Register/Log In Pages

### ISSUE THREAD

**Issue by awizemann** [miiikkeyyyy/larastart#2]
Freshly installed and testing and noticed that ReCAPTCHA isn't loading on Register/Login but I do see a "broken" plug in box flash on every page - assuming that might be it trying to fire - it only shows for milliseconds and then goes away. There are no errors and I tested in multiple browsers.

**Comment by awizemann** [comment]
Nevermind, I didn't see that I needed keys for the service. Added keys, works now.

**Comment by miiikkeyyyy** [comment]
Hello, awizemann.

I hope you are happy with what I've done so far. 
I am continuing to update this, and as we are in development mode it's always worth coming back to check on updates. 

If you have any features you want implemented, or any other suggestions, let me know :)
